zeebe:
  gateway:
    address: 127.0.0.1:26500
    plaintext: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/auth/realms/camunda-platform # Thay bằng realm của bạn
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG